### ISSUE TITLE
error on openOptionsPage

### ISSUE THREAD

**Issue by mia-zhao** [antfu-collective/vitesse-webext#171]
### Describe the bug

When clicking the "Open Options" button of pop up, error `Uncaught TypeError: Cannot read properties of undefined (reading 'openOptionsPage')` is thrown on `browser.runtime.openOptionsPage()`.
![Screenshot from 2024-04-01 23-00-48](https://github.com/antfu/vitesse-webext/assets/7109551/c44cce6a-6392-43b8-aacf-ce237b24ab88)

### Reproduction

1. pnpm dev 2. open extension pop up 3. click "Open Options" 4. option page won't open, observed error Uncaught TypeError: Cannot read properties of undefined (reading 'openOptionsPage')

### System Info

```Shell
System:
    OS: Linux 6.5 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 504.36 MB / 7.66 GB
    Container: Yes
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.6.2 - /usr/bin/node
    Yarn: 1.22.21 - /usr/bin/yarn
    npm: 10.5.0 - /usr/bin/npm
    pnpm: 8.15.2 - /usr/bin/pnpm
    bun: 1.0.35 - ~/.bun/bin/bun
  Browsers:
    Chromium: 123.0.6312.86
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by mia-zhao** [comment]
I don't quite understand the error behind. But I played around a bit, manually importing `import browser from 'webextension-polyfill'` in `Popup.vue` or updating the auto import config `'webextension-polyfill': [
            ['*', 'browser'],
          ],`  to `'webextension-polyfill': [
            ['default', 'browser'],
          ],` seems to fix the undefined error

**Comment by tmkx** [comment]
updating the auto import config `'webextension-polyfill': [ ['*', 'browser'], ],` to `'webextension-polyfill': [ ['default', 'browser'], ],` works in dev, but breaks in production.

it seems like a bug in the unplugin-auto-import (not sure), PRs welcome :)

**Comment by mia-zhao** [comment]
hi @tmkx thanks for following up. It does look like a limitation of unplugin-auto-import. 

Based on the generated code from unplugin-auto-import, when '`webextension-polyfill': [ ['*', 'browser'] ]` is configured, the Browser type is generated correctly (however, the browser object imported is not - the actual browser alias needed is in fact `browser.default`, and thus the reason `browser.runtime` is undefined). Likewise, if '`webextension-polyfill': [ ['default', 'browser'] ]` is used, the imported object is correct (while Browser type is not).

**Comment by zreren** [comment]
> updating the auto import config `'webextension-polyfill': [ ['*', 'browser'], ],` to `'webextension-polyfill': [ ['default', 'browser'], ],` works in dev, but breaks in production.将自动导入配置 `'webextension-polyfill': [ ['*', 'browser'], ],` 更新为 `'webextension-polyfill': [ ['default', 'browser'], ],` 在 dev 中有效，但在生产中中断。
> 
> it seems like a bug in the unplugin-auto-import (not sure), PRs welcome :)这似乎是 unplugin-auto-import 中的一个错误（不确定），PR 欢迎:)

That works for me

**Comment by Rebuilding127** [comment]
> > updating the auto import config `'webextension-polyfill': [ ['*', 'browser'], ],` to `'webextension-polyfill': [ ['default', 'browser'], ],` works in dev, but breaks in production.
> > it seems like a bug in the unplugin-auto-import (not sure), PRs welcome :)
> 
> That works for me

me too

**Comment by Rebuilding127** [comment]
I have another problem. 
After updating `"webextension-polyfill": [["*", "browser"]],` to `"webextension-polyfill": [["default", "browser"]],`, it can run without error, but the type prompt for `browser` is no longer available.

**Comment by Rebuilding127** [comment]
> I have another problem. After updating `"webextension-polyfill": [["*", "browser"]],` to `"webextension-polyfill": [["default", "browser"]],`, it can run without error, but the type prompt for `browser` is no longer available.

I restored `"webextension-polyfill": [["default", "browser"]],` to `"webextension-polyfill": [["*", "browser"]],`, then add `import browser from "webextension-polyfill"` in `Popup.vue`, it works.
But I'm not sure if this is correct, hope there is a better solution.

**Comment by imba97** [comment]
遇到同样的问题，本来改成了 `default`，但类型变成了 `any`

想着去掉 `auto-import.d.ts` 里面的类型，自己声明个类型，又发现 `unimport` 这个库有问题，配置 `dtsDisabled` 没反应，跑去改了改

但又感觉以后都要自己加类型太麻烦，转了一圈回来还是研究一下这个问题

目前小修了一下，应该可以了，不知道还有没有更好的方法
