### ISSUE TITLE
docs: update components README plugin name and link

### ISSUE THREAD

**Issue by RuSenLi** [antfu-collective/vitesse-webext#172]
#### update plguin name and link.
I'm happy to submit pr if needed. 
https://github.com/antfu-collective/vitesse-webext/blob/main/src/components/README.md?plain=1

`[vite-plugin-components](https://github.com/antfu/vite-plugin-components)` to `[unplugin-vue-components](https://github.com/unplugin/unplugin-vue-components)`

`[vite-plugin-icons](https://github.com/antfu/vite-plugin-icons)` to `[unplugin-icons](https://github.com/unplugin/unplugin-icons)`

**Comment by tmkx** [comment]
PR welcome :)
